spring:
  application:
    name: spring-boot-init
  datasource:
    url: jdbc:postgresql://postgres-db:5432/mydatabase
    username: mydb
    password: mypassword
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

jwt:
  secret: ${JWT_SECRET:myVerySecretKeyForJWTTokenGeneration123456789}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    net.devgrr.springbootinit: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN