spring:
  application:
    name: spring-boot-init
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: mydb
    password: mypassword
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /index.html
    tags-sorter: alpha
    operations-sorter: alpha

jwt:
  secret: myVerySecretKeyForJWTTokenGeneration123456789
  expiration: 86400000
